version: '3'

services:
  sse-proxy-service:
    build:
      context: ./sse-proxy
      dockerfile: ./images/Dockerfile
    #ports:
    #  - 8001:8001

  nginx-service:
    build:
      context: ./nginx
      dockerfile: ./images/Dockerfile
    ports:
      - 80:80
    depends_on:
      - sse-proxy-service